name: drag_select_grid_view_example
description: Demonstrates how to use the drag_select_grid_view package.
publish_to: 'none'

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  drag_select_grid_view:
    path: ../

flutter:
  uses-material-design: true